spring:
  profiles:
    active: -dev
---
server:
  port: 9527
spring:
  application:
    name: MICROSERVICE-ZUUL-GATEWAY
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: geteway-9527.com
    prefer-ip-address: true
zuul:
  prefix: "/aigou"
  ignored-services: "*"
  routes:
    sbUser.serviceId: plat-service
    sbUser.path: /plat/**
    productUser.serviceId: product-service
    productUser.path: /product/**
---
server:
  port: 9528
spring:
  application:
    name: MICROSERVICE-ZUUL-TEST
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: geteway-9527.com
    prefer-ip-address: true
zuul:
  prefix: "/aigou"
  ignored-services: "*"
  routes:
    sbUser.serviceId: plat-service
    sbUser.path: /plat/**
    productUser.serviceId: product-service
    productUser.path: /product/**
    
    